" ========= VUNDLE CONFIG ===========
set nocompatible
filetype off
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()
Plugin 'gmarik/Vundle.vim'


" " LIST PLUGINS HERE

" unimpaired
Plugin 'tpope/vim-unimpaired'

" sensible
Plugin 'tpope/vim-sensible'


" syntaxchecking and linting
Plugin 'scrooloose/syntastic'
set statusline+=%#warningmsg#
set statusline+=%{SyntasticStatuslineFlag()}
set statusline+=%*

let g:syntastic_always_populate_loc_list = 1
let g:syntastic_auto_loc_list = 1
let g:syntastic_check_on_open = 1
let g:syntastic_check_on_wq = 0

" " VUNDLE CLEANUP
call vundle#end()
filetype plugin indent on


" ============ general vim settings ============
" custom keybindings
noremap j gj
noremap k gk

" fix bold colors
set term=rxvt-unicode

set hlsearch
set is

syntax sync fromstart
syntax on

set background=dark
set showcmd
set showmatch
set ignorecase
set smartcase
set nojoinspaces
set scrolloff=3
set timeoutlen=0
set modeline

set tabstop=8
set shiftwidth=8
set expandtab

set cc=120

set completeopt=menu,menuone,longest,preview

" the default was just horrid
colorscheme peachpuff

highlight Identifier ctermfg=53
highlight Pmenu ctermbg=16 ctermfg=79
highlight PmenuSel ctermbg=49 ctermfg=79
highlight ErrorMsg ctermbg=32 ctermfg=79
highlight Search ctermbg=none ctermfg=29
highlight MatchParen ctermbg=none ctermfg=31
highlight ColorColumn ctermbg=80
highlight SpellBad ctermfg=1 ctermbg=none
highlight SpellCap ctermfg=none ctermbg=none
highlight SpellRare ctermfg=none ctermbg=none
highlight SpellLocal ctermfg=3 ctermbg=none
highlight mailURL ctermfg=2
highlight mailEmail ctermfg=5

" match extra whitespace
highlight ExtraWhitespace ctermbg=darkgreen guibg=darkgreen
match ExtraWhitespace /\s\+$\| \+\ze\t/
autocmd InsertEnter * match ExtraWhitespace /\s\+\%#\@<!$/
autocmd InsertLeave * match ExtraWhitespace /\s\+$/

" custom aliases
command Reply :%s/^\t/> /g

command -bang -bar Quit q<bang>
command -bang -bar -nargs=? -complete=file -range=% Write <line1>,<line2>w<bang> <args>

set autoindent

" auto-load correct highlighting highlighting
au BufNewFile,BufRead *.frag,*.vert,*.fp,*.vp,*.glsl setf glsl
au BufNewFile,BufRead *.vpy setf python
